Regenerated zphp command

diff --git a/zphp b/zphp
--- a/zphp
+++ b/zphp
@@ -37,9 +37,10 @@ zphp_usage() {
   echo
   # :command.usage_commands
   printf "Commands:\n"
-  echo "  run        Run the PHP binary or a PHP script"
-  echo "  composer   Run a composer command using the given PHP version"
-  echo "  switch     Switch the default version of PHP selected"
+  echo "  completions   Generate bash autocompletions script"
+  echo "  run           Run the PHP binary or a PHP script"
+  echo "  composer      Run a composer command using the given PHP version"
+  echo "  switch        Switch the default version of PHP selected"
   echo
 
   # :command.long_usage
@@ -52,6 +53,40 @@ zphp_usage() {
     echo
     echo "  --version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+zphp_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "zphp completions - Generate bash autocompletions script\n"
+    echo
+
+  else
+    printf "zphp completions - Generate bash autocompletions script\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  zphp completions\n"
+  printf "  zphp completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+    printf "  eval \"\$(zphp completions)\"\n"
     echo
 
   fi
@@ -397,7 +432,101 @@ config_has_key() {
   [[ $(config_get "$1") ]]
 }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# zphp completion                                          -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/dannyben/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_zphp_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $'  '
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_zphp_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    \'composer\'*\'--php\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "AUTO 5.6 7.3 7.4 8.0 8.1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--help -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'run\'*\'--php\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "AUTO 5.6 7.3 7.4 8.0 8.1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'composer\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--help --php -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'c\'*\'--php\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "AUTO 5.6 7.3 7.4 8.0 8.1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'r\'*\'--php\')'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "AUTO 5.6 7.3 7.4 8.0 8.1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'switch\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--help -h 5.6 7.3 7.4 8.0 8.1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'run\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--expose-port --help --php -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'r\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--expose-port --help --php -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'c\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--help --php -h")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    \'s\'*)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--help -h 5.6 7.3 7.4 8.0 8.1")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_zphp_completions_filter "--help --version -h -v c completions composer r run s switch")" -- "$cur" )'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'complete -F _zphp_completions zphp'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # :command.command_functions
+# :command.function
+zphp_completions_command() {
+  # src/completions_command.sh
+  send_completions
+
+}
+
 # :command.function
 zphp_run_command() {
   # src/run_command.sh
@@ -481,6 +610,13 @@ parse_requirements() {
   -* )
     ;;
 
+  completions )
+    action="completions"
+    shift
+    zphp_completions_parse_requirements "$@"
+    shift $#
+    ;;
+
   run | r )
     action="run"
     shift
@@ -514,6 +650,44 @@ parse_requirements() {
     ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+    -?* )
+      printf "invalid option: %s\n" "$key" >&2
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
+      printf "invalid argument: %s\n" "$key" >&2
+      exit 1
+
+      ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+zphp_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  case "${1:-}" in
+  --help | -h )
+    long_usage=yes
+    zphp_completions_usage
+    exit
+    ;;
+
+  esac
+
+  # :command.command_filter
+  action="completions"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -768,7 +942,15 @@ run() {
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
-  if [[ $action == "run" ]]; then
+  if [[ $action == "completions" ]]; then
+    if [[ ${args[--help]:-} ]]; then
+      long_usage=yes
+      zphp_completions_usage
+    else
+      zphp_completions_command
+    fi
+
+  elif [[ $action == "run" ]]; then
     if [[ ${args[--help]:-} ]]; then
       long_usage=yes
       zphp_run_usage
